### ISSUE TITLE
Not Converting dynamic data

### ISSUE THREAD

**Issue by suryanadiminti99** [Gkemon/Android-XML-to-PDF-Generator#20]
Hi , @Gkemon 
First thanks to your work. 

I can create pdf file using XML, But If add dynamic data to my layout views, it not reflect in pdf. Again it is showing static layouts data . data is came from previous activity using Intents.

**Comment by fazekasarn** [comment]
Hi, @suryanadiminti99 

Did you manage to solve this issue? I think I am facing something similar, I have a layout with DataBinding, I do inflate the layout, set the binding, but non of the binded texts appear in my pdf.

**Comment by poetrasapoetra** [comment]
I'm facing same issue using RecyclerView, then i use LinearLayout and my data is printed to pdf output

**Comment by Gkemon** [comment]
Hi , everyone. First thanks for using my library. Here I illustrated how to print pdf for dynamic content ( For example - An invoice or Report) https://github.com/Gkemon/Android-XML-to-PDF-Generator#how-to-print-an-invoice-or-report- . If you anyone of you can't get this then knock me again. Thank you. 
Tagging: @suryanadiminti99  @poetrasapoetra  @fazekasarn

**Comment by Gkemon** [comment]
Hi @suryanadiminti99 @poetrasapoetra @fazekasarn 
Thank you all for the support. Please kindly star and fork and send me the app links you all are using it. If there is no confidentiality then I will list them in my **readme.md** file.

**Comment by poetrasapoetra** [comment]
Hi, @Gkemon
Sorry for late reply and many thanks for your work. I used this library to make app named karst survey, but until now that app not yet finished (I don't know if it will be) because I no longer working on this app. This library is very helpful to make report like this.
![Screenshot_2022-08-22-16-59-21-740_com microsoft office officehubrow](https://user-images.githubusercontent.com/28970039/185895127-2c24a1f9-5f26-4821-ad43-f96c4da5aef9.jpg)
