### ISSUE TITLE
In version 2.5, can't call setPageSize function.

### ISSUE THREAD

**Issue by momersaleem** [Gkemon/Android-XML-to-PDF-Generator#35]
I am using version 2.5, can't call setPageSize function. Please guide how to use it.

**Comment by momersaleem** [comment]
Any help please?

**Comment by Gkemon** [comment]
@momersaleem  Sorry for the late reply. I remove these functions as the pdf file size will be now generated from XML's `android:layout_width` and `android:layout_height` size. Because for some use cases I noticed that setting size manually sometimes corrupts the pdf view. If facing any trouble then comment here or my email. I will try to help you. Thank you

**Comment by Gkemon** [comment]
Hi @momersaleem 
Thank you all for the support. Please kindly star and fork and send me the app links you all are using it. If there is no confidentiality then I will list them in my **readme.md** file.
