### ISSUE TITLE
Cannot Auto rescale document

### ISSUE THREAD

**Issue by skillFocus16** [Gkemon/Android-XML-to-PDF-Generator#8]
the document is generated but the words can’t be read unless zoomed in or out. Can I auto rescale the document to fit the words instead of zooming everytime i want to read the pdf? 

![447BF02E-1BD4-4181-AF1C-4AE07193B9BF](https://user-images.githubusercontent.com/19538491/102597231-64794380-412b-11eb-95bd-9bdbb16cd4d0.png)

**Comment by Gkemon** [comment]
Yeah. The trick is that just increase the TextView's textSize. Please knock me here if it doesn't work.

**Comment by skillFocus16** [comment]
Thank you @Gkemon. Increasing TextView's textsize will change the whole format of how the app's activity should be. Meaning, before downloading, the activity will have bigger fonts than the rest of the activities-

Apologies for the late feedback

**Comment by Gkemon** [comment]
@skillFocus16  Thanks for your feedback. It can be done with changing the size of the text view dynamically. Currently in my library,there is no feature to do that , so first of all sorry for that. And I can feel that changing textview in library , could create some side effect in library because it will hamper the [SOLID ](https://en.wikipedia.org/wiki/SOLID) principle . But I can suggest some step -

**Step 1:**  We can use [ssp ](https://github.com/intuit/ssp) in your text view size. It library says that it can handle the size dynamically. 

**Step 2:** If step 1 doesn't work ,  can change the text size of your layout with the [programitical approach ](https://stackoverflow.com/questions/6761625/dynamically-change-font-size-in-android) before downloading.

Please kindly inform me if you try the following steps and if you face any trouble then let me know. I will try to help you.
